title: Dalfox
description: Dalfox is a powerful open-source XSS scanner and utility focused on automation.
theme: just-the-docs
logo: "/images/logo-wide.png"
favicon_ico: "favicon.ico"
url: https://dalfox.hahwul.com


color_scheme: dalfox

aux_links:
  Github: https://github.com/hahwul/dalfox
  Go: https://pkg.go.dev/github.com/hahwul/dalfox/v2
  v2.10.0: https://github.com/hahwul/dalfox/releases/tag/v2.10.0

plugins:
  - jekyll-sitemap

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/hahwul/dalfox" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

permalink: pretty

# Collection settings
collections:
  advanced:
    permalink: "/:collection/:path/"
    output: true
  community:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    advanced:
      name: Advanced
    community:
      name: Community

mermaid:
  version: "10.9.1"

# Security.txt
security_txt:
  comment: If you find any security issues on this site, please contact me!
  contact: https://github.com/hahwul/dalfox/security
  canonical: https://owasp-noir.github.io/.well-known/security.txt
  preferred_languages: "en, ko"