---
name: CI Docker
on:
  push:
    branches: [main]
    paths:
      - cmd/**/*
      - pkg/**/*
      - lib/**/*
      - go.mod
      - dalfox.go
      - Dockerfile
  pull_request:
    branches: [main]
    paths:
      - cmd/**/*
      - pkg/**/*
      - lib/**/*
      - go.mod
      - dalfox.go
      - Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hahwul/dalfox:$(date +%s)
