---
name: Coverage
on:
  push:
    branches: [main]
    paths:
      - pkg/**/*
      - lib/**/*
      - go.mod
      - dalfox.go
      - Dockerfile
      - codecov.yml
  pull_request:
    branches: [main]
    paths:
      - pkg/**/*
      - lib/**/*
      - go.mod
      - dalfox.go
      - Dockerfile
      - codecov.yml
  workflow_dispatch:
    inputs:
      logLevel:
        description: manual run
        required: false
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.24'
      - name: Run coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
